<?php


namespace Klix\Api;


interface RefundReason
{
	const PRODUCT_OUT_OF_STOCK = 'PRODUCT_OUT_OF_STOCK';
	const RETURNED_PRODUCT = 'RETURNED_PRODUCT';
	const CANCELLED_SERVICE = 'CANCELLED_SERVICE';
	const PRICE_ADJUSTMENT = 'PRICE_ADJUSTMENT';
	const OTHER_REFUND = 'OTHER_REFUND';
	const RESERVATION_EXPIRED = 'RESERVATION_EXPIRED';
}
